"""HTML 落地页生成器 - 生成可部署的 TikTok Shop 商品页面"""

import os
from datetime import datetime

OUTPUT_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(__file__))), "data", "pages")
os.makedirs(OUTPUT_DIR, exist_ok=True)

PAGE_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{title}</title>
    <meta name="description" content="{description_short}">
    <meta name="keywords" content="{seo_tags}">
    <meta property="og:title" content="{title}">
    <meta property="og:description" content="{description_short}">
    <style>
        * {{ margin:0; padding:0; box-sizing:border-box; }}
        body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; color: #1a1a1a; background: #fff; }}
        .hero {{ background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 60px 20px; text-align: center; }}
        .hero h1 {{ font-size: 2rem; max-width: 700px; margin: 0 auto 16px; line-height: 1.3; }}
        .hero p {{ font-size: 1.1rem; opacity: 0.9; max-width: 600px; margin: 0 auto; }}
        .badge {{ display: inline-block; background: rgba(255,255,255,0.2); padding: 6px 16px; border-radius: 20px; font-size: 0.85rem; margin-bottom: 20px; }}
        .container {{ max-width: 800px; margin: 0 auto; padding: 40px 20px; }}
        .price-box {{ background: #f8f9fa; border-radius: 12px; padding: 24px; text-align: center; margin: 30px 0; }}
        .price {{ font-size: 2.5rem; font-weight: 700; color: #e53e3e; }}
        .price-original {{ font-size: 1.1rem; color: #999; text-decoration: line-through; margin-left: 8px; }}
        .promo {{ background: #fff3cd; color: #856404; padding: 12px 20px; border-radius: 8px; text-align: center; font-weight: 600; margin: 16px 0; }}
        .section {{ margin: 40px 0; }}
        .section h2 {{ font-size: 1.4rem; margin-bottom: 16px; padding-bottom: 8px; border-bottom: 2px solid #eee; }}
        .bullet {{ display: flex; align-items: flex-start; gap: 12px; padding: 12px 0; border-bottom: 1px solid #f0f0f0; }}
        .bullet .check {{ color: #38a169; font-size: 1.2rem; flex-shrink: 0; }}
        .bullet p {{ font-size: 0.95rem; line-height: 1.5; }}
        .review {{ background: #f8f9fa; border-radius: 10px; padding: 20px; margin: 12px 0; }}
        .review .stars {{ color: #f6ad55; margin-bottom: 8px; }}
        .review p {{ font-size: 0.9rem; line-height: 1.6; color: #555; font-style: italic; }}
        .cta {{ text-align: center; margin: 40px 0; }}
        .cta a {{ display: inline-block; background: #e53e3e; color: white; padding: 16px 48px; border-radius: 8px; font-size: 1.1rem; font-weight: 600; text-decoration: none; }}
        .cta a:hover {{ background: #c53030; }}
        .pain-point {{ background: #fff5f5; border-left: 4px solid #e53e3e; padding: 16px 20px; margin: 12px 0; border-radius: 0 8px 8px 0; }}
        .sections-list {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 16px; }}
        .section-card {{ background: #f8f9fa; border-radius: 10px; padding: 20px; text-align: center; }}
        .section-card .num {{ width: 32px; height: 32px; background: #667eea; color: white; border-radius: 50%; display: inline-flex; align-items: center; justify-content: center; font-weight: 700; font-size: 0.85rem; margin-bottom: 8px; }}
        .section-card h3 {{ font-size: 0.95rem; margin-bottom: 6px; }}
        .section-card p {{ font-size: 0.8rem; color: #666; }}
        footer {{ text-align: center; padding: 30px; color: #999; font-size: 0.8rem; border-top: 1px solid #eee; margin-top: 40px; }}
    </style>
</head>
<body>
    <div class="hero">
        <div class="badge">&#128293; As Seen On TikTok - {views} Views</div>
        <h1>{title}</h1>
        <p>{description_short}</p>
    </div>

    <div class="container">
        <div class="price-box">
            <span class="price">${price}</span>
            <span class="price-original">${original_price}</span>
            <div class="promo">{promo_text}</div>
        </div>

        <div class="section">
            <h2>&#10003; Why You'll Love It</h2>
            {bullets_html}
        </div>

        <div class="section">
            <h2>&#128172; What Customers Are Saying</h2>
            {reviews_html}
        </div>

        {pain_point_html}

        <div class="cta">
            <a href="#">&#128722; Buy Now - Limited Stock!</a>
        </div>

        {sections_html}

        <div class="section">
            <h2>&#127991; Tags</h2>
            <div style="display:flex;flex-wrap:wrap;gap:8px;">
                {tags_html}
            </div>
        </div>
    </div>

    <footer>
        &copy; {year} | Generated by AI Trade Agent System
    </footer>
</body>
</html>"""


class PageGenerator:
    """生成可部署的 HTML 商品落地页"""

    def generate(self, page_data: dict, product: dict = None) -> dict:
        """根据 AI 生成的内容数据，生成完整 HTML 页面

        page_data: AI 生成的结构化内容（page_title, description, bullet_points 等）
        product: 原始商品数据（价格、销量等）
        """
        product = product or {}
        price = product.get("price", 9.99)

        # 构建 HTML 片段
        bullets = page_data.get("bullet_points", [])
        bullets_html = "\n".join(
            f'<div class="bullet"><span class="check">&#10003;</span><p>{b}</p></div>'
            for b in bullets
        )

        reviews = page_data.get("review_templates", [])
        reviews_html = "\n".join(
            f'<div class="review"><div class="stars">&#9733;&#9733;&#9733;&#9733;&#9733;</div><p>"{r}"</p></div>'
            for r in reviews
        )

        tags = page_data.get("seo_tags", [])
        tags_html = " ".join(
            f'<span style="background:#edf2f7;padding:6px 14px;border-radius:20px;font-size:0.85rem;">{t}</span>'
            for t in tags
        )

        pain = page_data.get("pain_points", "")
        pain_point_html = ""
        if pain:
            pain_point_html = f'<div class="section"><h2>&#9888; Common Problems We Solve</h2><div class="pain-point">{pain}</div></div>'

        sections = page_data.get("landing_page_sections", [])
        sections_html = ""
        if sections:
            cards = "\n".join(
                f'<div class="section-card"><div class="num">{i+1}</div><h3>{s.get("title","")}</h3><p>{s.get("content","")}</p></div>'
                for i, s in enumerate(sections)
            )
            sections_html = f'<div class="section"><h2>&#128196; Product Details</h2><div class="sections-list">{cards}</div></div>'

        # 生成完整 HTML
        html = PAGE_TEMPLATE.format(
            title=page_data.get("page_title", product.get("title", "Product")),
            description_short=(page_data.get("description", "")[:160]),
            seo_tags=", ".join(tags),
            views=self._format_number(product.get("video_views", 0)),
            price=f"{price:.2f}",
            original_price=f"{price * 1.5:.2f}",
            promo_text=page_data.get("price_suggestion", "Buy 2 Get 1 FREE - Limited Time!"),
            bullets_html=bullets_html,
            reviews_html=reviews_html or '<p style="color:#999;">No reviews yet.</p>',
            pain_point_html=pain_point_html,
            sections_html=sections_html,
            tags_html=tags_html,
            year=datetime.now().year,
        )

        # 保存文件
        import hashlib
        slug = hashlib.md5(page_data.get("page_title", "page").encode()).hexdigest()[:8]
        filename = f"product_{slug}.html"
        filepath = os.path.join(OUTPUT_DIR, filename)
        with open(filepath, "w", encoding="utf-8") as f:
            f.write(html)

        return {
            "filename": filename,
            "filepath": filepath,
            "html": html,
            "html_length": len(html),
            "has_bullets": len(bullets),
            "has_reviews": len(reviews),
            "has_sections": len(sections),
            "preview_url": f"/pages/{filename}",
        }

    def _format_number(self, n: int) -> str:
        if n >= 1_000_000:
            return f"{n / 1_000_000:.1f}M"
        if n >= 1_000:
            return f"{n / 1_000:.1f}K"
        return str(n)
